apiVersion: apps/v1
kind: Deployment
metadata:
  name:  1fewrngg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 1fewrngg
  template:
    metadata:
      labels:
        app: 1fewrngg
    spec:
      containers:
      - image: okteto.dev/1fewrngg:latest
        name: 1fewrngg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "57127da7-4f5a-417b-9e87-d0c3a32e9210"
        - name: Vless_Path
          value: "/2hrth1"
        - name: Vmess_UUID
          value: "b88e6ecf-4d8e-46cf-8a89-9ba3c42e6db7"
        - name: Vmess_Path
          value: "/2mjdytjty1"
        - name: Share_Path
          value: "/share233"
