apiVersion: v1
kind: Service
metadata:
  name: 1fewrngg
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "1fewrngg"
    port: 8080
  selector:
    app: 1fewrngg
